# Use this as a template for your release signing properties.
# Copy to onlyreminder-release-key.properties and update values.
# DO NOT COMMIT THE REAL .properties OR .jks FILES.
RELEASE_STORE_FILE=../onlyreminder-release-key.jks
RELEASE_STORE_PASSWORD=your_store_password
RELEASE_KEY_ALIAS=onlyreminder_alias
RELEASE_KEY_PASSWORD=your_key_password
